### ISSUE TITLE
In master branch, ml_exp.py still has "S2" problem

### ISSUE THREAD

**Issue by TimoTokki** [kalray/metalibm#14]
```
32 from sollya import (
33     S2, Interval, round, inf, sup, log, expm1, log2,
34     guessdegree, dirtyinfnorm, floor
35 )
```

**Comment by TimoTokki** [comment]
Then I try to fix the bug according to the commit e75a0ee,  found that **metalibm_core/utility/num_utils.py** also has “S2” problem.
After fixing the bugs in the two files, everything is OK.

**Comment by nibrunie** [comment]
Hi @TimoTokki , 
    Thank youfor reporting the issue. Indeed, fixing S2 import issue that arises with new pythonsollya version was not propagated everywhere. I will try to do an overpass soon but if you have a fix of your own and can send a pull request I will be happy to merge it.

Regards

**Comment by TimoTokki** [comment]
@nibrunie ,
I am very happy to contribute my own modifications. I have sended a pull request just now. But I'm not familiar with git, so there may be some errors.

**Comment by nibrunie** [comment]
Pull request accepted with small modifications. It should fix the issue.
 Thank you a lot for your contirbution.
